services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db-setup:
        condition: service_completed_successfully
      db:
        condition: service_healthy

  db-setup:
    build:
      context: .
      target: builder
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
    command: npm run db:migrate

  db:
    # Use a specific major version for predictability
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      # This check verifies that the database is ready to accept connections.
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
