# FROM microsofts nodejs+postgres image (CHECK VERSION!!!!)
FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm

# Set the working directory to match the workspaceFolder in devcontainer.json
WORKDIR /workspaces

# Install convenience tools (nvim etc)